poll_seconds: 1.0
request_limit: 5000
concurrency: 5
default_min_value_rub: 2000000
send_history_on_start: false
send_start_message: false
max_seen_per_ticker: 50000

engine: stock
market: shares
board: TQBR

tickers:
  - ticker: SBER
    min_value_rub: 2000000

  - ticker: GAZP
    min_value_rub: 2000000

  - ticker: LKOH
    min_value_rub: 2000000

  - ticker: YDEX
    min_value_rub: 2000000

  - ticker: ROSN
    min_value_rub: 2000000

  - ticker: MGNT
    min_value_rub: 2000000
